# components/base/instruction.component.toml

[component]
name = "Instruction"
description = "A simple, reusable instruction component for providing clear guidance"
version = "1.0.0"

[props.text]
  type = "string"
  description = "The instruction text to display"
  required = true

[props.priority]
  type = "string"
  description = "The priority level ('normal', 'high', 'critical')"
  required = false
  default = "normal"

[props.format]
  type = "string"
  description = "Format style ('plain', 'emphasized', 'numbered')"
  required = false
  default = "plain"

[template]
content = """
{%- if props.format == "emphasized" -%}
**{{ props.text }}**
{%- elif props.format == "numbered" -%}
1. {{ props.text }}
{%- else -%}
{{ props.text }}
{%- endif -%}
{%- if props.priority == "high" %} ⚠️ (High Priority)
{%- elif props.priority == "critical" %} 🚨 (CRITICAL)
{%- endif -%}
"""

[targets]
  [targets.cursor]
    auto_include = true
    always_apply = false
    command = "On 'Generate'" 